const countryCodes = {
    "Abkhazia": { code: ["7", "840", "940"], iso: "AB" },
    "Afghanistan": { code: "93", iso: "AF" },
    "Åland": { code: ["358", "18"], iso: "AX" },
    "Albania": { code: "355", iso: "AL" },
    "Algeria": { code: "213", iso: "DZ" },
    "American Samoa": { code: ["1", "684"], iso: "AS" },
    "Andorra": { code: "376", iso: "AD" },
    "Angola": { code: "244", iso: "AO" },
    "Anguilla": { code: ["1", "264"], iso: "AI" },
    "Antigua and Barbuda": { code: ["1", "268"], iso: "AG" },
    "Argentina": { code: "54", iso: "AR" },
    "Armenia": { code: "374", iso: "AM" },
    "Aruba": { code: "297", iso: "AW" },
    "Ascension": { code: "247", iso: "AC" },
    "Australia": { code: "61", iso: "AU" },
    "Austria": { code: "43", iso: "AT" },
    "Azerbaijan": { code: "994", iso: "AZ" },
    "Bahamas": { code: "1", iso: "BS" },
    "Bahrain": { code: "973", iso: "BH" },
    "Bangladesh": { code: "880", iso: "BD" },
    "Barbados": { code: "1", iso: "BB" },
    "Belarus": { code: "375", iso: "BY" },
    "Belgium": { code: "32", iso: "BE" },
    "Belize": { code: "501", iso: "BZ" },
    "Benin": { code: "229", iso: "BJ" },
    "Bermuda": { code: "1", iso: "BM" },
    "Bhutan": { code: "975", iso: "BT" },
    "Bolivia": { code: "591", iso: "BO" },
    "Bosnia and Herzegovina": { code: "387", iso: "BA" },
    "Botswana": { code: "267", iso: "BW" },
    "Brazil": { code: "55", iso: "BR" },
    "Brunei": { code: "673", iso: "BN" },
    "Bulgaria": { code: "359", iso: "BG" },
    "Burkina Faso": { code: "226", iso: "BF" },
    "Burundi": { code: "257", iso: "BI" },
    "Cabo Verde": { code: "238", iso: "CV" },
    "Cambodia": { code: "855", iso: "KH" },
    "Cameroon": { code: "237", iso: "CM" },
    "Canada": { code: "1", iso: "CA" },
    "Central African Republic": { code: "236", iso: "CF" },
    "Chad": { code: "235", iso: "TD" },
    "Chile": { code: "56", iso: "CL" },
    "China": { code: "86", iso: "CN" },
    "Colombia": { code: "57", iso: "CO" },
    "Comoros": { code: "269", iso: "KM" },
    "Congo (Congo-Brazzaville)": { code: "242", iso: "CG" },
    "Congo (Congo-Kinshasa)": { code: "243", iso: "CD" },
    "Costa Rica": { code: "506", iso: "CR" },
    "Croatia": { code: "385", iso: "HR" },
    "Cuba": { code: "53", iso: "CU" },
    "Cyprus": { code: "357", iso: "CY" },
    "Czechia (Czech Republic)": { code: "420", iso: "CZ" },
    "Denmark": { code: "45", iso: "DK" },
    "Djibouti": { code: "253", iso: "DJ" },
    "Dominica": { code: "1", iso: "DM" },
    "Dominican Republic": { code: "1", iso: "DO" },
    "Ecuador": { code: "593", iso: "EC" },
    "Egypt": { code: "20", iso: "EG" },
    "El Salvador": { code: "503", iso: "SV" },
    "Equatorial Guinea": { code: "240", iso: "GQ" },
    "Eritrea": { code: "291", iso: "ER" },
    "Estonia": { code: "372", iso: "EE" },
    "Eswatini (fmr. 'Swaziland')": { code: "268", iso: "SZ" },
    "Ethiopia": { code: "251", iso: "ET" },
    "Fiji": { code: "679", iso: "FJ" },
    "Finland": { code: "358", iso: "FI" },
    "France": { code: "33", iso: "FR" },
    "Gabon": { code: "241", iso: "GA" },
    "Gambia": { code: "220", iso: "GM" },
    "Georgia": { code: "995", iso: "GE" },
    "Germany": { code: "49", iso: "DE" },
    "Ghana": { code: "233", iso: "GH" },
    "Greece": { code: "30", iso: "GR" },
    "Grenada": { code: "1", iso: "GD" },
    "Guatemala": { code: "502", iso: "GT" },
    "Guinea": { code: "224", iso: "GN" },
    "Guinea-Bissau": { code: "245", iso: "GW" },
    "Guyana": { code: "592", iso: "GY" },
    "Haiti": { code: "509", iso: "HT" },
    "Honduras": { code: "504", iso: "HN" },
    "Hungary": { code: "36", iso: "HU" },
    "Iceland": { code: "354", iso: "IS" },
    "India": { code: "91", iso: "IN" },
    "Indonesia": { code: "62", iso: "ID" },
    "Iran": { code: "98", iso: "IR" },
    "Iraq": { code: "964", iso: "IQ" },
    "Ireland": { code: "353", iso: "IE" },
    "Israel": { code: "972", iso: "IL" },
    "Italy": { code: "39", iso: "IT" },
    "Jamaica": { code: "1", iso: "JM" },
    "Japan": { code: "81", iso: "JP" },
    "Jordan": { code: "962", iso: "JO" },
    "Kazakhstan": { code: "7", iso: "KZ" },
    "Kenya": { code: "254", iso: "KE" },
    "Kiribati": { code: "686", iso: "KI" },
    "Korea, North": { code: "850", iso: "KP" },
    "Korea, South": { code: "82", iso: "KR" },
    "Kuwait": { code: "965", iso: "KW" },
    "Kyrgyzstan": { code: "996", iso: "KG" },
    "Laos": { code: "856", iso: "LA" },
    "Latvia": { code: "371", iso: "LV" },
    "Lebanon": { code: "961", iso: "LB" },
    "Lesotho": { code: "266", iso: "LS" },
    "Liberia": { code: "231", iso: "LR" },
    "Libya": { code: "218", iso: "LY" },
    "Liechtenstein": { code: "423", iso: "LI" },
    "Lithuania": { code: "370", iso: "LT" },
    "Luxembourg": { code: "352", iso: "LU" },
    "Madagascar": { code: "261", iso: "MG" },
    "Malawi": { code: "265", iso: "MW" },
    "Malaysia": { code: "60", iso: "MY" },
    "Maldives": { code: "960", iso: "MV" },
    "Mali": { code: "223", iso: "ML" },
    "Malta": { code: "356", iso: "MT" },
    "Marshall Islands": { code: "692", iso: "MH" },
    "Mauritania": { code: "222", iso: "MR" },
    "Mauritius": { code: "230", iso: "MU" },
    "Mexico": { code: "52", iso: "MX" },
    "Micronesia": { code: "691", iso: "FM" },
    "Moldova": { code: "373", iso: "MD" },
    "Monaco": { code: "377", iso: "MC" },
    "Mongolia": { code: "976", iso: "MN" },
    "Montenegro": { code: "382", iso: "ME" },
    "Morocco": { code: "212", iso: "MA" },
    "Mozambique": { code: "258", iso: "MZ" },
    "Myanmar (Burma)": { code: "95", iso: "MM" },
    "Namibia": { code: "264", iso: "NA" },
    "Nauru": { code: "674", iso: "NR" },
    "Nepal": { code: "977", iso: "NP" },
    "Netherlands": { code: "31", iso: "NL" },
    "New Zealand": { code: "64", iso: "NZ" },
    "Nicaragua": { code: "505", iso: "NI" },
    "Niger": { code: "227", iso: "NE" },
    "Nigeria": { code: "234", iso: "NG" },
    "North Macedonia": { code: "389", iso: "MK" },
    "Norway": { code: "47", iso: "NO" },
    "Oman": { code: "968", iso: "OM" },
    "Pakistan": { code: "92", iso: "PK" },
    "Palau": { code: "680", iso: "PW" },
    "Palestine": { code: "970", iso: "PS" },
    "Panama": { code: "507", iso: "PA" },
    "Papua New Guinea": { code: "675", iso: "PG" },
    "Paraguay": { code: "595", iso: "PY" },
    "Peru": { code: "51", iso: "PE" },
    "Philippines": { code: "63", iso: "PH" },
    "Poland": { code: "48", iso: "PL" },
    "Portugal": { code: "351", iso: "PT" },
    "Qatar": { code: "974", iso: "QA" },
    "Romania": { code: "40", iso: "RO" },
    "Russia": { code: "7", iso: "RU" },
    "Rwanda": { code: "250", iso: "RW" },
    "Saint Kitts and Nevis": { code: "1", iso: "KN" },
    "Saint Lucia": { code: "1", iso: "LC" },
    "Saint Vincent and the Grenadines": { code: "1", iso: "VC" },
    "Samoa": { code: "685", iso: "WS" },
    "San Marino": { code: "378", iso: "SM" },
    "Saudi Arabia": { code: "966", iso: "SA" },
    "Senegal": { code: "221", iso: "SN" },
    "Serbia": { code: "381", iso: "RS" },
    "Seychelles": { code: "248", iso: "SC" },
    "Sierra Leone": { code: "232", iso: "SL" },
    "Singapore": { code: "65", iso: "SG" },
    "Slovakia": { code: "421", iso: "SK" },
    "Slovenia": { code: "386", iso: "SI" },
    "Solomon Islands": { code: "677", iso: "SB" },
    "Somalia": { code: "252", iso: "SO" },
    "South Africa": { code: "27", iso: "ZA" },
    "South Sudan": { code: "211", iso: "SS" },
    "Spain": { code: "34", iso: "ES" },
    "Sri Lanka": { code: "94", iso: "LK" },
    "Sudan": { code: "249", iso: "SD" },
    "Suriname": { code: "597", iso: "SR" },
    "Sweden": { code: "46", iso: "SE" },
    "Switzerland": { code: "41", iso: "CH" },
    "Syria": { code: "963", iso: "SY" },
    "Taiwan": { code: "886", iso: "TW" },
    "Tajikistan": { code: "992", iso: "TJ" },
    "Tanzania": { code: "255", iso: "TZ" },
    "Thailand": { code: "66", iso: "TH" },
    "Timor-Leste": { code: "670", iso: "TL" },
    "Togo": { code: "228", iso: "TG" },
    "Tonga": { code: "676", iso: "TO" },
    "Trinidad and Tobago": { code: "1", iso: "TT" },
    "Tunisia": { code: "216", iso: "TN" },
    "Turkey": { code: "90", iso: "TR" },
    "Turkmenistan": { code: "993", iso: "TM" },
    "Tuvalu": { code: "688", iso: "TV" },
    "Uganda": { code: "256", iso: "UG" },
    "Ukraine": { code: "380", iso: "UA" },
    "United Arab Emirates": { code: "971", iso: "AE" },
    "United Kingdom": { code: "44", iso: "GB" },
    "United States": { code: "1", iso: "US" },
    "Uruguay": { code: "598", iso: "UY" },
    "Uzbekistan": { code: "998", iso: "UZ" },
    "Vanuatu": { code: "678", iso: "VU" },
    "Vatican City": { code: "379", iso: "VA" },
    "Venezuela": { code: "58", iso: "VE" },
    "Vietnam": { code: "84", iso: "VN" },
    "Yemen": { code: "967", iso: "YE" },
    "Zambia": { code: "260", iso: "ZM" },
    "Zimbabwe": { code: "263", iso: "ZW" }
  };

  
const getCountryCodeFromName = (countryName) => {
    const country = Object.keys(countryCodes).find(
        (key) => key.toLowerCase() === countryName.toLowerCase()
    );
    return country ? countryCodes[country].code : undefined;
}

const getCountryNameFromCode = (code) => {
    const country = Object.keys(countryCodes).find((key) => {
        const codes = Array.isArray(countryCodes[key].code) ? countryCodes[key].code : [countryCodes[key].code];
        return codes.includes(code.toString());
    });
    return country || undefined;
}


const getCountryNameFromISO = (isoCode) => {
    const country = Object.keys(countryCodes).find((key) => countryCodes[key].iso === isoCode.toUpperCase());
    return country || undefined;
}

module.exports = {
    getCountryCodeFromName,
    getCountryNameFromCode,
    getCountryNameFromISO
}

